build:
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            - phpunit
imports:
    - php
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_sim: false
    php_cpd: false
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.
filter:
    excluded_paths:
        - tests/*