build:
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            -
                command: phpunit --coverage-clover=coverage/coverage.clover
                coverage:
                    file: coverage/coverage.clover
                    format: php-clover
filter:
    excluded_paths:
        - tests/*